name: Chain Configuration Change
description: Propose a change to the chain configuration
title: "[Chain Config]: "
labels: ["chain-config", "needs-review"]
assignees:
  - btb-finance/chain-admins
body:
  - type: markdown
    attributes:
      value: |
        Use this template to propose changes to the BTB Orbit chain configuration.
        Please ensure all security implications are considered.
  - type: dropdown
    id: config-type
    attributes:
      label: Configuration Type
      description: What aspect of the chain configuration needs to be changed?
      options:
        - Gas Parameters
        - Validator Set
        - Sequencer Configuration
        - Bridge Settings
        - AnyTrust Parameters
        - Network Parameters
        - Other
    validations:
      required: true
  - type: textarea
    id: current-config
    attributes:
      label: Current Configuration
      description: What is the current configuration value?
      render: json
    validations:
      required: true
  - type: textarea
    id: proposed-config
    attributes:
      label: Proposed Configuration
      description: What should the new configuration be?
      render: json
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this change necessary?
    validations:
      required: true
  - type: textarea
    id: impact-analysis
    attributes:
      label: Impact Analysis
      description: What are the potential impacts of this change?
      placeholder: |
        - Security implications:
        - Performance impact:
        - User experience:
        - Backward compatibility:
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: Change Urgency
      description: How urgent is this configuration change?
      options:
        - Critical (Requires Immediate Action)
        - High (Next Deployment)
        - Medium (Planned Release)
        - Low (Future Consideration)
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Verification Checklist
      description: Please verify the following before submitting
      options:
        - label: I have tested this configuration change in a local environment
          required: true
        - label: I have considered the security implications of this change
          required: true
        - label: This change has been reviewed by at least one other team member
          required: true
        - label: I have documented the rollback procedure
          required: true
