name: Security Vulnerability Report
description: Report a security vulnerability (private by default)
title: "[Security]: "
labels: ["security", "confidential"]
assignees:
  - btb-finance/security-team
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability, please follow our responsible disclosure process in SECURITY.md instead of creating a public issue.
  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability are you reporting?
      options:
        - Smart Contract Vulnerability
        - Chain Configuration Issue
        - Bridge Security Issue
        - Access Control Problem
        - Protocol Level Vulnerability
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a detailed description of the vulnerability
      placeholder: |
        Please include:
        - Where the vulnerability exists
        - How it can be exploited
        - Potential impact
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the vulnerability
      placeholder: |
        1. Configure environment with...
        2. Execute transaction with...
        3. Observe that...
    validations:
      required: true
  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: If available, provide a proof of concept or exploit code
      render: typescript
  - type: dropdown
    id: severity
    attributes:
      label: Assessed Severity
      description: How severe do you consider this vulnerability?
      options:
        - Critical (Immediate Threat)
        - High (Significant Risk)
        - Medium (Moderate Risk)
        - Low (Minor Risk)
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing the vulnerability, please provide them
  - type: checkboxes
    id: terms
    attributes:
      label: Security Report Agreement
      options:
        - label: I have read and followed the project's security policy
          required: true
        - label: I understand this report will be handled confidentially
          required: true
        - label: I have not and will not disclose this vulnerability publicly until authorized
          required: true
