name: Testnet Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: testnet

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create env file
      run: |
        echo "ARBITRUM_RPC=${{ secrets.ARBITRUM_GOERLI_RPC }}" >> .env
        echo "PRIVATE_KEY=${{ secrets.DEPLOYER_PRIVATE_KEY }}" >> .env
        echo "VALIDATOR_1_ADDRESS=${{ secrets.VALIDATOR_1_ADDRESS }}" >> .env
        echo "VALIDATOR_2_ADDRESS=${{ secrets.VALIDATOR_2_ADDRESS }}" >> .env
        echo "VALIDATOR_3_ADDRESS=${{ secrets.VALIDATOR_3_ADDRESS }}" >> .env
        echo "SEQUENCER_ADDRESS=${{ secrets.SEQUENCER_ADDRESS }}" >> .env
    
    - name: Deploy to testnet
      run: npx ts-node scripts/deploy-full-chain.ts
    
    - name: Save deployment artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-info
        path: chain-deployment-info.json
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: chain-deployment-info.json
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
